name: Android CI

on: [push]

jobs:
  unit-tests:
    name: Run unit tests in any push to the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      # - name: Run unit tests
      #   run: ./gradlew test
      # - name: Upload html test report
      #   uses: actions/upload-artifact@3
      #   with:
      #     name: index.html
      #     path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble  
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_outputs
          path: app/build/outputs
    
