name: Android CI

on: [push]

jobs:
  unit-tests:
    name: Run unit tests in any push to the repository
    runs-on: ubuntu-latest
    steps:
      - name: Temporary logs
        run: |
          echo "awoooooo"
          echo "[Payload] github.event.ref_type= ${{ github.event.ref_type }} , github.event.ref= ${{ github.event.ref }}"
          echo "[Env variables] github.ref= ${{ github.ref }}"

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: ./gradlew test

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

    
