name: Android CI

on: [push]

jobs:
  CI:
    name: Run CI tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup and execute Gradle 'build --scan' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_outputs
          path: app/build/outputs
    
